version: '3.8'

services:
  portainer:
    image: portainer/portainer-ce:latest
    container_name: portainer
    restart: unless-stopped
    ports:
      - "9000:8000"
      - "9443:9443"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - portainer_data:/data

  adminer-dev:
    image: adminer:4.8.1-standalone
    container_name: adminer-dev
    restart: unless-stopped
    ports:
      - '9080:8080' 
    networks:
      - internal-dev

volumes:
  portainer_data:

networks:
  internal-dev:
    external: false
    name: internal-dev




