version: '3.8'

services:
  portainer:
    image: portainer/portainer-ce:latest
    container_name: portainer
    restart: unless-stopped
    ports:
      - "9000:8000"
      - "9443:9443"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - portainer_data:/data
    networks:
      - internal-dev # must have name bellow

  adminer-dev:
    image: adminer:4.8.1-standalone
    container_name: adminer-dev
    restart: unless-stopped
    ports:
      - '9080:8080' 
    networks:
      - internal-dev
      - external-host # adminer must have external network

  postgres-dev:
    image: postgres:16.4-alpine
    container_name: postgres-dev
    user: '${MY_UID}:${MY_GID}' 
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    ports:
      - '5432:5432'
    volumes:
      - ./postgres-data/data-dev:/var/lib/postgresql/data
        - /etc/passwd:/etc/passwd:ro  # must have this too for v16, can use alpine

volumes:
  portainer_data:

networks:
  internal-dev:
    name: internal-dev
    external: false
  external-host:
    name: external-host
    external: true




