version: '3.8'

services:
  mysql-dev:
    image: mysql:8.3.0
    container_name: mysql-dev
    # restart: unless-stopped
    user: '${MY_UID}:${MY_GID}' # maybe
    environment:
      - MYSQL_ROOT_PASSWORD=password
    ports:
      - '3306:3306'
    volumes:
      - ./mysql-data/data-dev:/var/lib/mysql
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - default
      - external-host

networks:
  external-host:
    name: external-host
    external: true
  default:
    name: mysql-default
    external: false

